@startuml
title
クラス図
end title
hide empty members
 
 'ここに色々書いていくと、右に図ができるんです(´>ω<`)
 package 増田家{
 class なぁちゃん
 class ままちん
 class みかちゃん
 class パパちん
 }
 package たか家{
 class とびくん
 class 素子さん
 class 康雄さん
 class シロちゃん 
 }
 
 なぁちゃん -> とびくん:大好き
 なぁちゃん <- とびくん :大好き
 パパちん --> なぁちゃん:大事
 ままちん --> なぁちゃん:ごはん作る
 なぁちゃん <-- みかちゃん :色々買ってくれる

 素子さん -->とびくん  :ごはん作ってくれたり
 康雄さん -->とびくん  :パン焼いてくれる
 とびくん <-- シロちゃん   :コンピューターのこと聞いてくる
 
@end